#!/usr/bin/env bash
# Install nginx web server
sudo apt update
sudo apt install -y nginx

# Configure nginx to listen on port 80
sudo sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default

sudo service nginx restart

# Create a custom HTML file with "Hello World!" content
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null
