#!/usr/bin/env bash
# This script displays the PID along with the process  name, of process whose name contain the word bash

#script_pid=$$

#processes=$(ps -ef | awk -v script_pid="$script_pid" '/bash/ && !/awk/ {print $2, $8}')

#echo "$processes"
pgrep -1 bash
