#!/usr/bin/env bash
# This script displays the PID along with the process  name, of process whose name contain the word bash

processes=$(ps -eo pid,cmd | awk '/bash/ && !/awk/ {print $1, $2}')

echo "$processes"
