#!/usr/bin/env bash
# This script displays the username, user ID, and home directory path from /etc/passwd

while IFS='=' read -r username _ uid _ _ home _; do
	echo "$username:$uid:$home"
done < /etc/passwd
