#!/usr/bin/env bash
# This script displays "Best School" 10 times, but says "Hi" on the 9th iteration

i=0

while [ $i -lt 10 ]
do
	if [ $i -eq 8 ]; then
		echo "Hi"
	else
		echo "Best School"
	fi

	i=$((i+1))
done
