#!/usr/bin/env bash
# This script displays "Best School" 10 times, but says "Hi" on the 9th iteration

i=1

while [ $i -lt 10 ]
do
	echo "Best School"
	if [ $i = 8 ]
	then
		echo "Hi"
	fi

	(( i++ ))
done
